# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(362, 552)
        Calculator.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label = QtWidgets.QLabel(Calculator)
        self.label.setGeometry(QtCore.QRect(10, 3, 344, 78))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label.setStyleSheet("background-color: white")
        self.percentButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("%"))

        self.percentButton.setGeometry(QtCore.QRect(10, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("c"))
        self.cButton.setGeometry(QtCore.QRect(100, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(190, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(280, 90, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.plusButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("+"))
        self.plusButton.setGeometry(QtCore.QRect(280, 180, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.nineButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 180, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.sevenButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 180, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 180, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.minusButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(280, 270, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.sixButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 270, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fourButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 270, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.fiveButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 270, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.plusButton_2 = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("+"))
        self.plusButton_2.setGeometry(QtCore.QRect(280, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.plusButton_2.setFont(font)
        self.plusButton_2.setObjectName("plusButton_2")
        self.threeButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.oneButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.secondButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("2"))
        self.secondButton.setGeometry(QtCore.QRect(100, 360, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.secondButton.setFont(font)
        self.secondButton.setObjectName("secondButton")
        self.equalButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(280, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.decimalButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.decimal())
        self.decimalButton.setGeometry(QtCore.QRect(190, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.plusminusButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.plusminus())
        self.plusminusButton.setGeometry(QtCore.QRect(10, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")
        self.zeroButton = QtWidgets.QPushButton(Calculator, clicked=lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.label.setText(_translate("Calculator", "0"))
        self.percentButton.setText(_translate("Calculator", "%"))
        self.cButton.setText(_translate("Calculator", "c"))
        self.arrowButton.setText(_translate("Calculator", "<<"))
        self.divideButton.setText(_translate("Calculator", "/"))
        self.plusButton.setText(_translate("Calculator", "+"))
        self.nineButton.setText(_translate("Calculator", "9"))
        self.sevenButton.setText(_translate("Calculator", "7"))
        self.eightButton.setText(_translate("Calculator", "8"))
        self.minusButton.setText(_translate("Calculator", "-"))
        self.sixButton.setText(_translate("Calculator", "6"))
        self.fourButton.setText(_translate("Calculator", "4"))
        self.fiveButton.setText(_translate("Calculator", "5"))
        self.plusButton_2.setText(_translate("Calculator", "+"))
        self.threeButton.setText(_translate("Calculator", "3"))
        self.oneButton.setText(_translate("Calculator", "1"))
        self.secondButton.setText(_translate("Calculator", "2"))
        self.equalButton.setText(_translate("Calculator", "="))
        self.decimalButton.setText(_translate("Calculator", "."))
        self.plusminusButton.setText(_translate("Calculator", "+/-"))
        self.zeroButton.setText(_translate("Calculator", "0"))


    #calculation
    def math_it(self):
        screen=self.label.text()
        try:
            screen=eval(screen)
            self.label.setText(str(screen))
        except:
            self.label.setText("ERROR")

    # plusminuschange
    def plusminus(self):
        screen = self.label.text()
        if "-" in screen:
            screen = screen.replace("-", "")
            self.label.setText(f'{screen}')
        else:
            self.label.setText(f'-{screen}')


    # removelastletter
    def remove_it(self):
        screen = self.label.text()
        self.label.setText(f'{screen[:-1]}')

    # adding decimal
    def decimal(self):
        screen = self.label.text()
        self.count = 0
        for i in screen:
            if i==".":
                self.count +=1
            if self.count >0:
                screen.replace(".","")
                self.label.setText(f'{screen}')
            if i=="+":
                self.count=0
                r=screen.index(i)
                if screen[-1] == '.' or screen[r]:
                    pass
                else:
                    self.label.setText(f'{screen}.')
            else:
                if screen[-1] == '.':
                    pass
                else:
                    self.label.setText(f'{screen}.')
            if self.count > 0:
                screen.replace(".", "")
                self.label.setText(f'{screen}')

    # clear
    def press_it(self, pressed):
        if pressed == "c":
            self.label.setText("0")
        else:
            if self.label.text() == "0":
                self.label.setText("")
            else:
                self.label.setText(f'{self.label.text()}{pressed}')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
